export const PERMISSIONS = {
  EVENT_READ: 'event.read',
  EVENT_CREATE: 'event.create',
  EVENT_UPDATE: 'event.update',
  EVENT_FREEZE: 'event.freeze',
  PHOTO_READ: 'photo.read',
  PHOTO_RETOUCH_READ: 'photo.retouch.read',
  REVIEW_QUEUE_READ: 'dashboard.review_queue.read',
  ORDER_READ: 'order.read',
  PREVIEW_LINK_READ: 'preview_link.read',
  BUYER_READ: 'buyer.read',
  EVENT_COLLABORATOR_READ: 'event.collaborator.read',
  TENANT_READ: 'tenant.read',
  CONTRACT_READ: 'contract.read',
  CONTRACT_ISSUE: 'contract.issue',
  CONTRACT_REVOKE: 'contract.revoke',
  TENANT_PROFILE_READ: 'tenant.profile.read',
  TENANT_PROFILE_UPDATE: 'tenant.profile.update',
  TENANT_PAYOUT_METHOD_READ: 'tenant.payout_method.read',
  TENANT_PAYOUT_METHOD_MANAGE: 'tenant.payout_method.manage',
  TENANT_QUOTA_SET: 'tenant.quota.set',
  DASHBOARD_OPERATOR_READ: 'dashboard.operator.read',
  ORDER_GIFT: 'order.gift',
  ORDER_CONVERT_TO_GIFT: 'order.convert_to_gift',
  ORDER_CONVERT_TO_SALE: 'order.convert_to_sale',
} as const

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
